"""Generate an EO/IR pan-tilt camera tower as a Gazebo Classic model.

Derived from the gimbal_camera_mast model: a three-legged 2.5 m mast carrying a
yaw turntable, a tilting camera housing with an EO camera, and an IMU on the
moving head. The IR lens is cosmetic — see the note in the SDF.

The joints are driven only by ArduPilot. Each tower gets an ArduPilotPlugin
bound to its own FDM port, and an AntennaTracker SITL instance on the other end
turns MAVLink into servo output: SERVO1 -> pan, SERVO2 -> tilt. Nothing moves
the head from the Gazebo side, so there is exactly one owner of the joints.

Still a generator rather than a static model directory because every tower needs
a distinct model name and FDM port; the geometry itself is fixed.
"""

MATERIAL = "file://media/materials/scripts/gazebo.material"

MAST_H = 2.5        # ground to top of pole
PLATE_Z = 2.51
PAN_Z = 2.57
HEAD_Z = 2.70       # camera centre
FOOT_R = 0.85       # tripod foot radius
LEG_TOP = 1.10      # where the legs meet the mast
LEG_LEN = 1.390     # hypot(FOOT_R, LEG_TOP)
LEG_PITCH = 2.4843  # pi - atan2(FOOT_R, LEG_TOP): the leg runs DOWN and
                    # out from the mast to its foot. Using atan2 alone
                    # mirrors it in Z and the legs splay upward instead.


def _vis(name, pose, geom, colour, collide=True):
    """A visual, and by default the matching collision — the two are identical
    for every part of this model, and writing them separately invites drift."""
    out = f"""      <visual name="{name}_visual">
        <pose>{pose}</pose>
        <geometry>{geom}</geometry>
        <material><script><uri>{MATERIAL}</uri>
          <name>Gazebo/{colour}</name></script></material>
      </visual>
"""
    if collide:
        out += f"""      <collision name="{name}_collision">
        <pose>{pose}</pose>
        <geometry>{geom}</geometry>
      </collision>
"""
    return out


def _cyl(r, l):
    return f"<cylinder><radius>{r}</radius><length>{l}</length></cylinder>"


def _box(x, y, z):
    return f"<box><size>{x} {y} {z}</size></box>"


def _base():
    import math
    parts = [
        _vis("mast", f"0 0 {MAST_H/2} 0 0 0", _cyl(0.06, MAST_H), "Grey"),
        _vis("plate", f"0 0 {PLATE_Z} 0 0 0", _box(0.20, 0.20, 0.02), "Grey"),
    ]
    for i in range(3):
        az = i * 2.0 * math.pi / 3.0
        cx, cy = math.cos(az) * FOOT_R / 2.0, math.sin(az) * FOOT_R / 2.0
        parts.append(_vis(
            f"leg{i+1}", f"{cx:.4f} {cy:.4f} {LEG_TOP/2} 0 {LEG_PITCH} {az:.4f}",
            _cyl(0.03, LEG_LEN), "DarkGrey"))
        fx, fy = math.cos(az) * FOOT_R, math.sin(az) * FOOT_R
        parts.append(_vis(
            f"foot{i+1}", f"{fx:.4f} {fy:.4f} 0.015 0 0 0",
            _cyl(0.07, 0.03), "Black"))
    return "".join(parts)


def tower_sdf(name, fdm_addr="127.0.0.1", fdm_port=9012,
              listen_addr="0.0.0.0", eo=(640, 360), cam_port=8630,
              cameras="live"):
    """SDF for one camera tower, driven by AntennaTracker over fdm_port."""
    fdm_port_out = fdm_port + 1
    # cameras_on False: sensor inactive at rest, woken only if someone
    # actually opens the feed. Off costs nothing; llvmpipe renders every
    # active camera whether or not anything consumes it.
    cam_always = 1 if cameras == "live" else 0
    cam_sleep = 1 if cameras == "ondemand" else 0
    return f"""<?xml version="1.0" ?>
<!-- Generated by terrain/tower.py — edit that, not this. -->
<sdf version="1.6">
  <model name="{name}">

    <!-- Pinned to the world: a tower does not topple, and leaving it dynamic
         means the solver fights the heightmap under the feet. -->
    <joint name="world_fixed" type="fixed">
      <parent>world</parent>
      <child>base_link</child>
    </joint>

    <link name="base_link">
      <inertial>
        <pose>0 0 1.0 0 0 0</pose>
        <mass>25.0</mass>
        <inertia>
          <ixx>13.0</ixx><iyy>13.0</iyy><izz>9.0</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz>
        </inertia>
      </inertial>
{_base()}    </link>

    <joint name="pan_joint" type="revolute">
      <parent>base_link</parent>
      <child>pan_link</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit><lower>-3.14159</lower><upper>3.14159</upper>
          <effort>50</effort><velocity>3.0</velocity></limit>
        <dynamics><damping>0.30</damping><friction>0.05</friction></dynamics>
      </axis>
    </joint>

    <link name="pan_link">
      <pose>0 0 {PAN_Z} 0 0 0</pose>
      <inertial><mass>0.6</mass>
        <inertia><ixx>0.0008</ixx><iyy>0.0008</iyy><izz>0.0012</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>
{_vis("pan", "0 0 0 0 0 0", _cyl(0.07, 0.06), "White")}\
{_vis("fork_left", "0 0.09 0.06 0 0 0", _box(0.06, 0.02, 0.10), "White", False)}\
{_vis("fork_right", "0 -0.09 0.06 0 0 0", _box(0.06, 0.02, 0.10), "White", False)}\
    </link>

    <joint name="tilt_joint" type="revolute">
      <parent>pan_link</parent>
      <child>tilt_link</child>
      <axis>
        <xyz>0 1 0</xyz>
        <!-- Down is +. Stopping at 70 deg keeps the mast and top
             plate outside the camera's 36 deg vertical FOV; at 90 deg the
             camera looks straight into its own mount. -->
        <limit><lower>-0.7854</lower><upper>1.2217</upper>
          <effort>30</effort><velocity>3.0</velocity></limit>
        <dynamics><damping>0.30</damping><friction>0.05</friction></dynamics>
      </axis>
    </joint>

    <link name="tilt_link">
      <pose>0 0 {HEAD_Z} 0 0 0</pose>
      <inertial><mass>1.2</mass>
        <inertia><ixx>0.0037</ixx><iyy>0.0107</iyy><izz>0.0110</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>
{_vis("housing", "0 0 0 0 0 0", _box(0.30, 0.14, 0.13), "White")}\
{_vis("eo_lens", "0.15 0.038 0 0 1.5708 0", _cyl(0.045, 0.05), "DarkGrey", False)}\
{_vis("eo_glass", "0.176 0.038 0 0 1.5708 0", _cyl(0.035, 0.005), "Black", False)}\
{_vis("ir_lens", "0.15 -0.038 0 0 1.5708 0", _cyl(0.04, 0.05), "DarkGrey", False)}\
{_vis("ir_glass", "0.176 -0.038 0 0 1.5708 0", _cyl(0.03, 0.005), "Black", False)}\

      <sensor name="eo_camera" type="camera">
        <pose>0.18 0.038 0 0 0 0</pose>
        <always_on>{cam_always}</always_on><update_rate>10</update_rate>
        <visualize>true</visualize>
        <camera name="eo">
          <horizontal_fov>1.047</horizontal_fov>
          <image><width>{eo[0]}</width><height>{eo[1]}</height><format>R8G8B8</format></image>
          <clip><near>0.05</near><far>1500</far></clip>
        </camera>
        <plugin name="camera_stream" filename="libCameraStreamPlugin.so">
          <port>{cam_port}</port>
          <label>{name} EO</label>
          <quality>70</quality>
          <shrink>1</shrink>
          <sleep_when_idle>{cam_sleep}</sleep_when_idle>
        </plugin>
      </sensor>

      <!-- The IR lens is visual only. There was an ir_camera sensor here, but
           it was type="camera" — a greyscale narrow-FOV render of the same
           visible scene, with no temperature anywhere in it. Gazebo Classic has
           no thermal sensor, so it could not cue on engine heat or a warm hull,
           and shipping it as "thermal" would have misled anyone relying on it.
           Removed rather than renamed: it also cost a full render pass per
           tower per frame. -->
    </link>

    <!-- AntennaTracker needs an attitude source for its head. -->
    <link name="imu_link">
      <pose>0 0 {HEAD_Z} 0 0 0</pose>
      <inertial><mass>0.01</mass>
        <inertia><ixx>1e-6</ixx><iyy>1e-6</iyy><izz>1e-6</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>
      <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on><update_rate>250</update_rate><imu/>
      </sensor>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent>tilt_link</parent><child>imu_link</child>
    </joint>

    <!-- Servo output from the tracker instance on {fdm_port}. POSITION control
         maps a 0..1 servo command to a joint angle as cmd*multiplier+offset,
         then a P loop drives the joint there. -->
    <plugin name="ardupilot_plugin" filename="libArduPilotPlugin.so">
      <!-- Without listen_addr the plugin binds 127.0.0.1 and SITL in another
           container cannot reach it. -->
      <listen_addr>{listen_addr}</listen_addr>
      <fdm_addr>{fdm_addr}</fdm_addr>
      <fdm_port_in>{fdm_port}</fdm_port_in>
      <!-- SITL instance I listens on 9003+10I. Without this the plugin
           replies to the default 9003 and every instance past the first
           hangs in lockstep waiting for state that never arrives. -->
      <fdm_port_out>{fdm_port_out}</fdm_port_out>
      <connectionTimeoutMaxCount>5</connectionTimeoutMaxCount>
      <lock_step>1</lock_step>
      <modelXYZToAirplaneXForwardZDown>0 0 0 3.141593 0 0</modelXYZToAirplaneXForwardZDown>
      <gazeboXYZToNED>0 0 0 3.141593 0 0</gazeboXYZToNED>
      <imuName>imu_sensor</imuName>
      <control channel="0">
        <type>POSITION</type><jointName>pan_joint</jointName>
        <!-- target = multiplier * (offset + cmd); cmd 0..1 -> -pi..+pi -->
        <offset>-0.5</offset><multiplier>6.283185</multiplier>
        <p_gain>3.0</p_gain><i_gain>0.0</i_gain><d_gain>0.15</d_gain>
        <cmd_max>3</cmd_max><cmd_min>-3</cmd_min>
      </control>
      <control channel="1">
        <type>POSITION</type><jointName>tilt_joint</jointName>
        <!-- cmd 0..1 -> PITCH_MIN..PITCH_MAX (70 down .. 45 up),
             so the full servo range lands exactly on the joint range and the
             loop never winds up against a stop in normal operation. -->
        <offset>-0.6087</offset><multiplier>-2.0071</multiplier>
        <p_gain>3.0</p_gain><i_gain>0.0</i_gain><d_gain>0.40</d_gain>
        <cmd_max>3</cmd_max><cmd_min>-3</cmd_min>
      </control>
    </plugin>

  </model>
</sdf>
"""


def tower_config(name):
    return f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.6">model.sdf</sdf>
  <author><name>Nick</name><email>nickaleks@ddc2.com</email></author>
  <description>Pan-tilt camera on a {MAST_H} m mast, driven by
  an ArduPilot AntennaTracker instance.</description>
</model>
"""


def write_tower(models_root, name, **kw):
    """Write models/<name>/{model.sdf,model.config}; returns the model dir."""
    d = models_root / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "model.sdf").write_text(tower_sdf(name, **kw))
    (d / "model.config").write_text(tower_config(name))
    return d
